"""
Sample ~1400 random valid-2021 Taiwan hours for the full-year generation set.

Draws from the same valid-2021 pool as make_eval_timestamps.py
(`cwb_valid & all era5_valid & year==2021`), subtracts the timestamps already in
the val/test split YAMLs (so the year sample is disjoint from both), then picks
--n distinct hours with a fixed --seed and writes a flat `{times: [...]}` YAML.

Because the pool is the CWB valid set, every sampled hour is guaranteed to exist
on Taiwan (not all of 2021 is present) — and Europa, which has every 2021 hour,
trivially contains the same subset. Run once on Alex and commit the result:

    apptainer exec ~/apptainer/corrdiff_zarr3.sif python3 make_year_sample.py \
        --data-path /anvme/workspace/b214cb18-ws-daniel3/b214cb18-ws-daniel-cwb-1779073861/cwa_dataset \
        --exclude conf/val_times_2021.yaml --exclude conf/test_times_2021.yaml \
        --output conf/exp_static2019_1_reg/year2021_random1400.yaml --n 1400 --seed 0
"""
import argparse
import sys
from pathlib import Path

import numpy as np
import yaml

from make_eval_timestamps import load_valid_times_2021, to_iso


def load_exclude(paths: list) -> set:
    """Collect all ISO timestamps from one or more {times: [...]} YAML files."""
    excluded = set()
    for p in paths:
        with open(p) as f:
            data = yaml.safe_load(f)
        excluded.update(data.get("times", []) or [])
    return excluded


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Sample disjoint full-year 2021 timestamps.")
    parser.add_argument("--data-path", type=str, required=True,
                        help="Path to CWA zarr dataset (defines the valid-2021 pool).")
    parser.add_argument("--output", type=str, required=True,
                        help="Output YAML file (flat {times: [...]} mapping).")
    parser.add_argument("--exclude", type=str, action="append", default=[],
                        help="YAML file(s) whose `times` are removed from the pool. Repeatable.")
    parser.add_argument("--n", type=int, default=1400,
                        help="Number of distinct timestamps to sample. Default: 1400")
    parser.add_argument("--seed", type=int, default=0,
                        help="Random seed for reproducibility. Default: 0")
    args = parser.parse_args()

    print(f"🚀 Opening zarr dataset: {args.data_path}")
    valid_2021 = load_valid_times_2021(args.data_path)
    pool_iso = [to_iso(t) for t in valid_2021]
    print(f"Found {len(pool_iso)} valid timestamps in 2021.")

    excluded = load_exclude(args.exclude)
    if args.exclude:
        print(f"Excluding {len(excluded)} val/test timestamps from {len(args.exclude)} file(s).")

    pool = sorted(set(pool_iso) - excluded)
    print(f"Disjoint pool size: {len(pool)}")
    if len(pool) < args.n:
        print(f"❌ only {len(pool)} disjoint timestamps available, need {args.n}.",
              file=sys.stderr)
        sys.exit(1)

    rng = np.random.default_rng(args.seed)
    picked_idx = rng.choice(len(pool), size=args.n, replace=False)
    picked = sorted(pool[i] for i in picked_idx)

    overlap = set(picked) & excluded
    if overlap:
        print(f"❌ sampled timestamps overlap exclude set: {overlap}", file=sys.stderr)
        sys.exit(1)

    header = (
        f"# Generated by make_year_sample.py\n"
        f"# Source: {args.data_path}\n"
        f"# Year: 2021, seed: {args.seed}, n: {args.n}\n"
        f"# Disjoint from: {', '.join(args.exclude) if args.exclude else '(none)'}\n"
        f"# Full-year generation set (random valid-2021 hours, exists on Taiwan & Europa)\n\n"
    )
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write(header)
        yaml.safe_dump({"times": picked}, f, default_flow_style=False, sort_keys=False)

    print(f"✓ Wrote {len(picked)} timestamps to {out}")


if __name__ == "__main__":
    main()
